version: 2
aliases:
  - &deploy_ssh_fingerprint "e8:d7:da:b8:6a:fb:75:50:8d:5f:48:61:3c:46:49:50"

  - &container_config
    docker:
      - image: renovate/renovate:latest
        environment:
          DEPLOY_SSH_FINGERPRINT: *deploy_ssh_fingerprint
          RENOVATE_CONFIG_FILE: renovate-config.js

  - &step_setup_git
    run:
      name: Setup git
      command: |
        mkdir -p "${HOME}/.ssh/"
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > "${HOME}/.ssh/config"
        DEPLOY_SSH_FILE="${DEPLOY_SSH_FINGERPRINT//:}"
        DEPLOY_SSH_FILE="${HOME}/.ssh/id_rsa_${DEPLOY_SSH_FILE//\"}"
        if [ -f "${DEPLOY_SSH_FILE}" ]; then
          echo "Found Deploy SSH key file ${DEPLOY_SSH_FILE}"
          ssh-add -D > /dev/null
          ssh-add "${DEPLOY_SSH_FILE}"
        fi
        git config --global user.name "$DEPLOY_USER_NAME"
        git config --global user.email "$DEPLOY_USER_EMAIL"

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
#      - add_ssh_keys:
#          fingerprints:
#            - *deploy_ssh_fingerprint
#      - *step_setup_git
      - run: renovate

workflows:
  version: 2
  main:
    jobs:
      - build
